name: nhaa_stress_assessment
description: "AI-Based Real-Time Stress and Trauma Assessment Module for NHAA"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  google_fonts: ^8.2.1
  url_launcher: ^6.3.2
  http: ^1.2.2
  record: ^7.1.1
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
