"""initial_phase9_schema

Revision ID: dbe85f4987b4
Revises: 
Create Date: 2026-09-16 15:25:44.269776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbe85f4987b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responders',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('RESPONDER', 'SUPERVISOR', 'ADMIN', name='responder_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responders_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_responders_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_responders_username'), ['username'], unique=True)

    op.create_table('cases',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('external_case_reference', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_REVIEW', 'AWAITING_RESPONDER_ACTION', 'ACTION_RECORDED', 'CLOSED', name='case_status', native_enum=False), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('consent_status', sa.String(length=50), nullable=False),
    sa.Column('assigned_responder_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_responder_id'], ['responders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_assigned_responder_id'), ['assigned_responder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_external_case_reference'), ['external_case_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)
        batch_op.create_index('ix_cases_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('assessments',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_version', sa.String(length=20), nullable=False),
    sa.Column('assessment_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index('ix_assessments_case_created', ['case_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_created_at'), ['created_at'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('event_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index('ix_audit_events_case_actor_created', ['case_id', 'actor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_conversations_case_session', ['case_id', 'session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_session_id'), ['session_id'], unique=True)

    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('supporting_indicators', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('responder_action', sa.Text(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('responder_decision', sa.String(length=30), nullable=True),
    sa.Column('responder_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_recommendations_case_status_created', ['case_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_status'), ['status'], unique=False)

    op.create_table('svi_results',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('svi_version', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=20), nullable=False),
    sa.Column('factor_contributions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('key_drivers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('uncertainties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('immediate_safety_attention', sa.Boolean(), nullable=False),
    sa.Column('urgent_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('svi_results', schema=None) as batch_op:
        batch_op.create_index('ix_svi_case_created_risk', ['case_id', 'created_at', 'risk_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_svi_results_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_svi_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_svi_results_risk_category'), ['risk_category'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_type', sa.Enum('VICTIM', 'SYSTEM', 'RESPONDER', name='message_sender_type', native_enum=False), nullable=False),
    sa.Column('input_source', sa.Enum('TEXT', 'VOICE', name='message_input_source', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conv_timestamp', ['conversation_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index('ix_messages_conv_timestamp')

    op.drop_table('messages')
    with op.batch_alter_table('svi_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_svi_results_risk_category'))
        batch_op.drop_index(batch_op.f('ix_svi_results_created_at'))
        batch_op.drop_index(batch_op.f('ix_svi_results_case_id'))
        batch_op.drop_index('ix_svi_case_created_risk')

    op.drop_table('svi_results')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_status'))
        batch_op.drop_index(batch_op.f('ix_recommendations_created_at'))
        batch_op.drop_index('ix_recommendations_case_status_created')
        batch_op.drop_index(batch_op.f('ix_recommendations_case_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_session_id'))
        batch_op.drop_index('ix_conversations_case_session')
        batch_op.drop_index(batch_op.f('ix_conversations_case_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_case_id'))
        batch_op.drop_index('ix_audit_events_case_actor_created')
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_created_at'))
        batch_op.drop_index(batch_op.f('ix_assessments_case_id'))
        batch_op.drop_index('ix_assessments_case_created')

    op.drop_table('assessments')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index('ix_cases_status_created_at')
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_external_case_reference'))
        batch_op.drop_index(batch_op.f('ix_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_cases_assigned_responder_id'))

    op.drop_table('cases')
    with op.batch_alter_table('responders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responders_username'))
        batch_op.drop_index(batch_op.f('ix_responders_role'))
        batch_op.drop_index(batch_op.f('ix_responders_email'))

    op.drop_table('responders')
    # ### end Alembic commands ###
